name: api_exception
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  firebase_auth: ^5.1.3
  freezed_annotation: ^2.4.4
  internet_connection_checker: ^2.0.0
  firebase_storage: ^12.1.2
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0


dev_dependencies:
  freezed: ^2.5.2
  very_good_analysis: ^6.0.0
# build_runner: ^2.4.11
# freezed: ^2.5.7
# lints: ^3.0.0
# test: ^1.24.0
