name: kewsa
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  #*Mono repos
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  users_repository:
    path: packages/users_repository
  api_exception:
    path: packages/api_exception

  #* State management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #* Network
  dio: ^5.6.0

  #* Data class
  equatable: ^2.0.5

  #* Firebase
  firebase_core: ^3.5.0

  #* Routing
  flow_builder: ^0.1.0

  #* UI
  font_awesome_flutter: ^10.1.0
  formz: ^0.6.0
  meta: ^1.15.0
  flutter_video_info: ^1.3.2
  shimmer: ^3.0.0
  circular_menu: ^4.0.0
  flutter_slidable: ^3.1.1

  #* Playes
  fc_native_video_thumbnail: ^0.9.0
  video_player: ^2.9.1

  #* Pick files
  image_picker: ^1.0.7

  #* Managing Directories
  path_provider: ^2.1.2

  #* Network image diffrent state handling
  cached_network_image: ^3.3.1
  fpdart: ^1.1.0

  #* Util
  intl: ^0.19.0
  csv: ^6.0.0

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  #* Test
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  #* for analyse packages
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/res.csv

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
