// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZwmUzL6NmqpI6lMGeLtBdd4v5sj8cEAY',
    appId: '1:380720915021:web:6e8252d19f4e6cd0073204',
    messagingSenderId: '380720915021',
    projectId: 'kewsa-b3f15',
    authDomain: 'kewsa-b3f15.firebaseapp.com',
    storageBucket: 'kewsa-b3f15.appspot.com',
    measurementId: 'G-7196ZS07MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6RxeEbGMb57-mnvfftbobCsHuZn3epI0',
    appId: '1:380720915021:android:4111c2fd33c85e17073204',
    messagingSenderId: '380720915021',
    projectId: 'kewsa-b3f15',
    storageBucket: 'kewsa-b3f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsTW7E9JnNPJ8Q3sMlYbYdj5-80eBZlzM',
    appId: '1:380720915021:ios:9efd2b05368ed7e4073204',
    messagingSenderId: '380720915021',
    projectId: 'kewsa-b3f15',
    storageBucket: 'kewsa-b3f15.appspot.com',
    iosBundleId: 'com.savad.kewsa',
  );
}
